"""
Generate src/version.f90.inc from fpm.toml's version field.

PpqFort_version() (src/PpqFort_m.f90) reports the package version at
runtime as three integers.  Those constants used to be hand-typed in
Fortran source, with a comment asking whoever bumped fpm.toml's version to
also update them -- easy to forget (and it was: v1.1.0 and v1.1.1 both
shipped reporting 1.1.0).  This script removes the second copy: run it,
and PpqFort_version() always reports exactly what fpm.toml says, because
there is nothing left to keep in sync by hand.

Run this before `fpm build`/`fpm test` (every Dockerfile does; for a local,
non-container build, run it yourself first -- src/version.f90.inc is not
committed, so PpqFort_m.f90's `include` fails loudly if you forget, rather
than silently building a stale version in):

    python scripts/generate_version_include.py

test/python/test_version.py checks the compiled library's reported version
against fpm.toml directly, so a stale include (generated once, fpm.toml
bumped again without re-running this) is still caught.
"""

import os
import re

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FPM_TOML = os.path.join(REPO_ROOT, "fpm.toml")
OUT_PATH = os.path.join(REPO_ROOT, "src", "version.f90.inc")

_VERSION_RE = re.compile(r'^\s*version\s*=\s*"(\d+)\.(\d+)\.(\d+)"\s*$', re.MULTILINE)


def read_version(fpm_toml=FPM_TOML):
    text = open(fpm_toml).read()
    m = _VERSION_RE.search(text)
    if not m:
        raise ValueError(f'{fpm_toml}: no line matching version = "X.Y.Z" '
                          "(semver, no pre-release/build suffix -- PpqFort_version() reports "
                          "three plain integers)")
    return tuple(int(g) for g in m.groups())


def write_include(version, out_path=OUT_PATH):
    major, minor, patch = version
    with open(out_path, "w") as f:
        f.write(
            "! Generated by scripts/generate_version_include.py from fpm.toml's version\n"
            "! field -- do not edit, and do not commit (see that script's docstring).\n"
            f"  integer(c_int), parameter :: version_major = {major}\n"
            f"  integer(c_int), parameter :: version_minor = {minor}\n"
            f"  integer(c_int), parameter :: version_patch = {patch}\n"
        )


if __name__ == "__main__":
    v = read_version()
    write_include(v)
    print(f"{OUT_PATH}: {'.'.join(map(str, v))} (from {FPM_TOML})")
